stages:
  - build
  - check

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - mvn compile
  artifacts:
    paths:
      - target

defprev-check:
  image: docker
  stage: check
  script:
    - docker run --rm ${SIBYL_IMAGE} --project-dir=target --token=${TOKEN}
