realFullTime : 5.0
resName : 16
pathToMeshFile : /home/bobo/IdeaProjects/DG/meshes/tunnel_and_border_2500.mesh
#pathToMeshFile : /home/bobo/IdeaProjects/galerkin_1/meshes/50_tr_1_domen.mesh
#pathToMeshFile : /home/bobo/IdeaProjects/DG/meshes/tunnel_and_border_2500.mesh
initialCondition :
  profile: cos
  width: 25.0
  amplitude: 1.0
  direction:
    x: 1.0
    y: 0.0
    z: 0.0
  center:
    x: 0.0
    y: 0.0
    z: 0.0

# Currently user must associate borders with borders' configs manually
# to do it user must go to be used .mesh file and find Vertices line
# All vertices described by 4 values {x, y, z, index}
# Index are set by Salome with the following logic:
#   1) Specific unique index is set to every corner point (like {50, 50, 0} and
#     {50, -50} in a square 50-50 mesh)
#   2) Specific unique inedes is set to every side ({50, 45}, {50, 2}, {50, -35}
#     will have the same index as they are all on the same side)
# Also this fourth index value in {...} is called 'edgeIndex' in Salome and
# can be seen there.
defaultBorderType: absorbing
# enclosed, free, absorbing
borders:
    # left
-   index: 3
    borderType: absorbing
    # bottom
-   index: 6
    borderType: enclosed
    # right
-   index: 8
    borderType: absorbing
    # top
-   index: 10
    borderType: enclosed

domains:
-   index: 0
    lambda: 2.0
    rho: 1.0
    mu: 1.0
-   index: 1
    lambda: 6.0
    rho: 7.0
    mu: 8.0
-   index: 2
    lambda: 2.0
    rho: 1.0
    mu: 1.0


#
#		<domains>
#			<domain>
#				<index>0</index>
#				<cp>2f</cp>
#				<cs>1f</cs>
#				<ro>1f</ro>
#			</domain>
#
#			<domain>
#				<index>1</index>
#				<cp>2f</cp>
#				<cs>1f</cs>
#				<ro>1f</ro>
#			</domain>
#
#			<domain>
#				<index>2</index>
#				<cp>2f</cp>
#				<cs>1f</cs>
#				<ro>1f</ro>
#			</domain>
#
#		</domains>