realFullTime : 100.0
spatialStep : 1.0
pathToMeshFile : /home/bobo/IdeaProjects/galerkin_1/meshes/Mesh_1.mesh
initialCondition : sin


#
#		<domains>
#			<domain>
#				<index>0</index>
#				<cp>2f</cp>
#				<cs>1f</cs>
#				<ro>1f</ro>
#			</domain>
#
#			<domain>
#				<index>1</index>
#				<cp>2f</cp>
#				<cs>1f</cs>
#				<ro>1f</ro>
#			</domain>
#
#			<domain>
#				<index>2</index>
#				<cp>2f</cp>
#				<cs>1f</cs>
#				<ro>1f</ro>
#			</domain>
#
#		</domains>