realFullTime : 100.0
spatialStep : 1.0
pathToMeshFile : /home/bobo/IdeaProjects/DG/meshes/new_100.mesh
#pathToMeshFile : /home/bobo/IdeaProjects/galerkin_1/meshes/50_tr_1_domen.mesh
#pathToMeshFile : /home/bobo/IdeaProjects/DG/meshes/tunnel_and_border_2500.mesh
initialCondition : sin
defaultBorderType: enclosed
domains:
-   index: 0
    lambda: 2.0
    rho: 1.0
    mu: 1.0
    borderType: enclosed
#-   index: 1
#    lambda: 2.0
#    rho: 1.0
#    mu: 1.0
#    borderType: enclosed
#-   index: 2
#    lambda: 2.0
#    rho: 1.0
#    mu: 1.0
#    borderType: enclosed


#
#		<domains>
#			<domain>
#				<index>0</index>
#				<cp>2f</cp>
#				<cs>1f</cs>
#				<ro>1f</ro>
#			</domain>
#
#			<domain>
#				<index>1</index>
#				<cp>2f</cp>
#				<cs>1f</cs>
#				<ro>1f</ro>
#			</domain>
#
#			<domain>
#				<index>2</index>
#				<cp>2f</cp>
#				<cs>1f</cs>
#				<ro>1f</ro>
#			</domain>
#
#		</domains>